# Generated by Django 5.1 on 2025-10-19 21:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('symbole', models.CharField(max_length=20, unique=True)),
                ('type_actif', models.CharField(choices=[('ACTION', 'Action'), ('ETF', 'ETF'), ('OBLIGATION', 'Obligation'), ('CRYPTO', 'Crypto'), ('FONDS', 'Fonds'), ('INDICE', 'Indice'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortefeuilleActif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_entree', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('poids', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('actif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app_portefeuille.actif')),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='app_portefeuille.portefeuille')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('portefeuille', 'actif'), name='unique_actif_par_portefeuille')],
            },
        ),
    ]
